export default {
    INCREMENT : 'INCREMENT',
    DECREMENT : 'DECREMENT',
    RESET : 'RESET',
    INPUT_CHANGE : 'INPUT_CHANGE',
    ITEM_CHANGE : 'ITEM_CHANGE',
    ITEM_SUBMIT : 'ITEM_SUBMIT',
    ITEM_DELETE : 'ITEM_DELETE',
}